version: '3.6'

services:
    pos-service:
        image: pos-service:v1
        container_name: pos-service
        build:
            context: .
            target: tmp
        volumes:
            - ../src:/code
            - ../run-data/wallet-data-dst:/root/.dstra
            - ../run-data/wallet-data-traw:/root/.traw
        command: tail -f /root/.bashrc
        depends_on:
            - pos-mysql
        networks:
          - pos-service-network

    pos-mysql:
        image: pos-mysql:v1
        container_name: pos-mysql
        build:
          context: .
          dockerfile: Dockerfile-mysql
        expose:
            - "3306"
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ../run-data/pos-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: posservice
        networks:
          - pos-service-network


networks:
  pos-service-network:
    driver: bridge
