version: '3.6'

services:
    pos-service:
        image: pos-service
        build:
            context: .
        container_name: pos-service
        hostname: pos-service
        volumes:
            - ../src:/code
            - ../run-data/wallet-data-dst:/root/.dstra
            - ../run-data/wallet-data-traw:/root/.traw
        tty: true
        depends_on:
            - pos-mysql
        networks:
          - pos-service-network
        extra_hosts:
            - "dl.discordapp.net:104.16.248.144"
            - "gateway.discord.gg:104.16.60.37"
            - "status.discordapp.com:104.16.11.231"
            - "cdn.discordapp.com:104.16.9.231"
            - "discordapp.com:104.16.59.5"
            - "media.discordapp.net:104.16.250.144"
            - "images-ext-2.discordapp.net:104.16.249.144"
            - "images-ext-1.discordapp.net:104.16.250.144"
            - "static-cdn.jtvnw.net:151.101.78.214"

    pos-mysql:
        image: pos-mysql
        build:
          context: .
          dockerfile: Dockerfile-mysql
        container_name: pos-mysql
        hostname: pos-mysql
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ../run-data/pos-mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: posservice
        networks:
          - pos-service-network


networks:
  pos-service-network:
    driver: bridge
